-- Реестр камер (создаётся автоматически Hibernate, скрипт для справки)
CREATE TABLE IF NOT EXISTS camera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    building VARCHAR(255),
    camera_url VARCHAR(255),
    esp_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL
);

-- Привязка мероприятия к камере (null — принимаются все камеры)
ALTER TABLE session
    ADD COLUMN IF NOT EXISTS camera_name VARCHAR(255);
